// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvsflxhdooilocdtyhps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2c2ZseGhkb29pbG9jZHR5aHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0OTUyODQsImV4cCI6MjA3MTA3MTI4NH0.opz2nkkyyxYoLKMaL8RWhvo5_aFOP5GLR_uJfRgxIdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});